<a href="https://colab.research.google.com/github/senjuti238/Machine-Learning-practice/blob/main/Day1_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [ ]:
# Is for mathematical operations

import numpy as np

a = [1,2,3,4,5]
arr1 = np.array(a)

b = [[1,2,3,4], [5,6,7,8]]
arr2 = np.array(b)

print(arr1)
print(arr2)

[1 2 3 4 5]
[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
print(type(a),
type(arr1),
type(b),
type(arr2),)

<class 'list'> <class 'numpy.ndarray'> <class 'list'> <class 'numpy.ndarray'>


In [ ]:
import sys
s = range(1000)
print("Size of each elements in the list in bytes", sys.getsizeof(s))
print("Complete list size in bytes", sys.getsizeof(s) * len(s))

Size of each elements in the list in bytes 48
Complete list size in bytes 48000


In [ ]:
#We are checking comparison between numpy size and noemal size of "sys" package

import numpy as np
s = np.arange(1000)
print("Size of each element in the list by bytes", s.itemsize)
print("Complete list size in bytes", s.size * s.itemsize)

Size of each element in the list by bytes 8
Complete list size in bytes 8000


In [ ]:
#Import time lib and make execution time taking by the system

import time

a = range(1000)
b = range(1000)

start = time.time()

ab = [(a * b) for a,b in zip(a,b)] #List Comprehension

end = time.time()

print("Total time taken", end - start)

Total time taken 0.0001704692840576172


In [ ]:
import numpy

arr1 = np.arange(1000)
arr2 = np.arange(1000)

start = time.time()

arr_mul = arr1 * arr2

end = time.time()

print("Total time taken", end - start)

Total time taken 8.273124694824219e-05


In [ ]:
lst1 = [1,2,3,4]

arr = np.array(lst1)

print(arr)

[1 2 3 4]


In [ ]:
print(lst1 + 1)

TypeError: ignored

In [ ]:
print(arr + 1)

[2 3 4 5]


In [ ]:
arr1 = np.array([[1,2,3,4], [5,6,7,8]], ndmin = 2)

print(arr1)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
arr2 = list(arr1)
print(arr2)

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]


In [ ]:
print(type(arr1),
type(arr2))

<class 'numpy.ndarray'> <class 'list'>


In [1]:
import numpy as np
arr1 = np.array([1,2,3])

print(arr1)

[1 2 3]


In [2]:
type(arr1)

numpy.ndarray

In [3]:
arr2 = np.zeros((2,2))

print(arr2)

[[0. 0.]
 [0. 0.]]


In [4]:
lst1 = [1,2,3,4.52, True, False, (2+3j), 'Codegnan']

print(lst1)

[1, 2, 3, 4.52, True, False, (2+3j), 'Codegnan']


In [5]:
type(lst1)

list

In [6]:
# Creating an n-dimensional array

a = [[1,2,3], [4,5,6]]

print(a)

[[1, 2, 3], [4, 5, 6]]


In [7]:
import numpy as np

np.array(a, ndmin = 10)

array([[[[[[[[[[1, 2, 3],
               [4, 5, 6]]]]]]]]]])

In [12]:
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
               
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
arr[2,0]

7

In [14]:
arr[3,0]

IndexError: ignored

In [15]:
np.random.rand(3,2)

array([[0.81271949, 0.53987777],
       [0.69742881, 0.84844106],
       [0.90012591, 0.94059878]])

In [16]:
arr1 = np.random.rand(3,2)

arr2 = np.random.rand(3,2)

sum1 = np.add(arr1, arr2)

print(arr1)
print(arr2)
print(sum1)

[[0.80067777 0.83481981]
 [0.95678854 0.62691512]
 [0.88083476 0.39250028]]
[[0.74749856 0.84465429]
 [0.94154267 0.21430994]
 [0.21877911 0.01460094]]
[[1.54817633 1.6794741 ]
 [1.89833121 0.84122506]
 [1.09961387 0.40710122]]


In [18]:
subtract1 = np.subtract(arr1, arr2)

print(subtract1)

[[ 0.05317922 -0.00983449]
 [ 0.01524587  0.41260519]
 [ 0.66205565  0.37789934]]


In [19]:
# Indexing and slicing

a = [1,2,3,7,20.5, "Codegnan", True]

a[5]

'Codegnan'

In [20]:
a[8]

IndexError: ignored

In [21]:
# Slicing = [start: end + 1]
a [0:6]

[1, 2, 3, 7, 20.5, 'Codegnan']

In [22]:
a[-1]

True

In [23]:
# Reshape an array

arr2 = np.array([[1,2,3,4],
         [5,6,7,8]])

arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [24]:
arr2.shape

(2, 4)

In [25]:
arr2.reshape(1,8)

array([[1, 2, 3, 4, 5, 6, 7, 8]])

## Pandas - Data Handling Mechanism. We need to upload a dataset and get the link to read the dataset

In [47]:
import pandas as pd

data = pd.read_csv("/content/ipl_matches.csv")

In [48]:
data.head()

id  season       city  ...         umpire1        umpire2 umpire3
0   1    2017  Hyderabad  ...     AY Dandekar       NJ Llong     NaN
1   2    2017       Pune  ...  A Nand Kishore         S Ravi     NaN
2   3    2017     Rajkot  ...     Nitin Menon      CK Nandan     NaN
3   4    2017     Indore  ...    AK Chaudhary  C Shamshuddin     NaN
4   5    2017  Bangalore  ...             NaN            NaN     NaN

[5 rows x 18 columns]

In [44]:
data.tail()

id  season       city  ...          umpire1          umpire2 umpire3
631  632    2016     Raipur  ...   A Nand Kishore     BNJ Oxenford     NaN
632  633    2016  Bangalore  ...     AK Chaudhary  HDPK Dharmasena     NaN
633  634    2016      Delhi  ...        M Erasmus    C Shamshuddin     NaN
634  635    2016      Delhi  ...        M Erasmus        CK Nandan     NaN
635  636    2016  Bangalore  ...  HDPK Dharmasena     BNJ Oxenford     NaN

[5 rows x 18 columns]

In [36]:
# we are using  html parser 

web = pd.read_html("https://en.wikipedia.org/wiki/States_and_union_territories_of_India")[3]

In [37]:
web.head()

State  ... Additional officiallanguages[39]
0     Andhra Pradesh  ...                                —
1  Arunachal Pradesh  ...                                —
2              Assam  ...                    Bengali, Bodo
3              Bihar  ...                             Urdu
4       Chhattisgarh  ...                    Chhattisgarhi

[5 rows x 11 columns]

In [40]:
excel = pd.read_excel("/content/ex1.xlsx")

In [41]:
excel.head()

Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

In [49]:
excel.tail()

Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo